### ISSUE TITLE
No sensor values in mqtt

### ISSUE THREAD

**Issue by Kartax** [MikeJMcGuire/hass-blueriiot#1]
Hi @MikeJMcGuire 

I have configured my Blue Connect (incl. Plus Subscription) and your Addon
but i dont seem to get the **values** of each sensor.

### log output:

> 13-06-2022 04:41:14.94 BlueRiiot.Run() [0x00000054]
13-06-2022 04:41:15.51 BlueRiiot.Run() [0x00000054] Pool "Unser Pool" (f3aaabbe-eb56-43e2-af8f-a3eb81d3e6c9) found.
13-06-2022 04:41:19.89 MQTT.SendMessage() hass-blueriiot/status
13-06-2022 04:46:19.89 MQTT.SendMessage() hass-blueriiot/status
13-06-2022 04:51:19.89 MQTT.SendMessage() hass-blueriiot/status
13-06-2022 04:56:19.89 MQTT.SendMessage() hass-blueriiot/status
13-06-2022 05:01:19.89 MQTT.SendMessage() hass-blueriiot/status
13-06-2022 05:06:19.89 MQTT.SendMessage() hass-blueriiot/status

### mqtt:
> **hass-blueriiot/status**
online

> **homeassistant/sensor/blueriiot/sensor_pool_ph/config**
{"name":"Pool pH","unique_id":"hass-blueriiot-1","device":{"identifiers":["hass-blueriiot"],"name":"Blueriiot Pool Sensor","model":"Container","manufacturer":"Blueriiot"},"state_topic":"sarah/sensor_pool/ph","availability_topic":"hass-blueriiot/status"}

(same for temperature, orp and salinity)

 
**=>** So there is only a config-json but not the value itself.
**=>** And what about `"state_topic":"sarah/sensor_pool/ph"` ?

**Comment by whizkid79** [comment]
Same issue here, but without Plus subscription. Any hints on this?

**Comment by Kartax** [comment]
As I did. Not get any faction here, I ended up using this adding:  https://github.com/LordMike/MBW.BlueRiiot2MQTT

Sorry @MikeJMcGuire

**Comment by MikeJMcGuire** [comment]
No probs, I use his library too in the add-on. Let me know if you want to continue looking into this.

**Comment by whizkid79** [comment]
Thanks @Kartax, I'll have a look.

**Comment by MikeJMcGuire** [comment]
Howdy - someone's offered to help me test it with their device. It looks like some devices report salinity and some conductivity. Releasing an update to pick that up.

**Comment by MikeJMcGuire** [comment]
Fixed in v2022.9.0.
