### ISSUE TITLE
No parameters are received

### ISSUE THREAD

**Issue by s0len** [MikeJMcGuire/hass-blueriiot#2]
Hi, 

I installed this a few weeks back and wasen't able to get it working out of the box. So I tried today again by double checking all the credentials and making sure it was correct. Still there is no data received. I'm using a Blue Connect Plus with a Blue Extender to receive the data via WIFI. Any clue on what might be the issue here?

This is my log:
27-06-2022 07:30:56.86 ServiceCore.Start() Built: Thu 06/01/2022 
27-06-2022 07:30:57.46 Configuration.GetConfiguration() Read BlueriiotUser
27-06-2022 07:30:57.46 BlueriiotUser: "my email"
27-06-2022 07:30:57.46 Configuration.GetConfiguration() Read BlueriiotPassword
27-06-2022 07:30:57.46 BlueriiotPassword: *******
27-06-2022 07:30:57.46 Configuration.GetConfiguration() Read MQTTUser
27-06-2022 07:30:57.46 MQTTUser: MQTTZ2M
27-06-2022 07:30:57.46 Configuration.GetConfiguration() Read MQTTPassword
27-06-2022 07:30:57.46 MQTTPassword: *******
27-06-2022 07:30:57.46 Configuration.GetConfiguration() Read MQTTBroker
27-06-2022 07:30:57.46 MQTTBroker: core-mosquitto:1883
27-06-2022 07:30:57.47 Configuration.GetConfiguration() Read MQTTTLS
27-06-2022 07:30:57.47 MQTTTLS: False
27-06-2022 07:30:57.48 MQTT.StartMQTT()
27-06-2022 07:30:57.72 MQTT.StartMQTT() Host: core-mosquitto, Port: 1883
27-06-2022 07:30:58.00 BlueRiiot.Start()
27-06-2022 07:30:58.35 ServiceCore.MQTTRegister()
27-06-2022 07:30:58.39 MQTT.SendMessage() homeassistant/sensor/blueriiot/sensor_pool_temperature/config
27-06-2022 07:30:58.41 MQTT.SendMessage() homeassistant/sensor/blueriiot/sensor_pool_ph/config
27-06-2022 07:30:58.41 MQTT.SendMessage() homeassistant/sensor/blueriiot/sensor_pool_orp/config
27-06-2022 07:30:58.41 MQTT.SendMessage() homeassistant/sensor/blueriiot/sensor_pool_salinity/config
27-06-2022 07:30:59.32 ASPNETCoreStartup.ConfigureServices()
27-06-2022 07:31:00.89 ASPNETCoreStartup.Configure()
27-06-2022 07:31:03.41 BlueRiiot.Run() [0x00000000]
27-06-2022 07:31:03.88 ASPNETCoreStartup.OnStarted()
27-06-2022 07:31:07.71 MQTT.SendMessage() hass-blueriiot/status
27-06-2022 07:31:09.87 BlueRiiot.Run() [0x00000000] Pool "Vattenpalatset" (26ca1484-1f0c-4045-a148-0491331451cd) found.
<img width="445" alt="2022-06-27" src="https://user-images.githubusercontent.com/35483234/175867198-60091732-1a42-4f69-a4d7-57cdb380e7c9.png">

**Comment by MikeJMcGuire** [comment]
Howdy - no, but happy to work with you to fix it. I've got very limited ability to test the add-on myself.

**Comment by MikeJMcGuire** [comment]
Leave a comment on here and I can contact you: https://blog.mikejmcguire.com/2021/12/30/home-assistant-add-on-for-blueriiot-blue-connect-plus/

**Comment by MikeJMcGuire** [comment]
Howdy - someone's offered to help me test it with their device. It looks like some devices report salinity and some conductivity. Releasing an update to pick that up.

**Comment by MikeJMcGuire** [comment]
Fixed in v2022.9.0.
