### ISSUE TITLE
can't get conductivity parameter

### ISSUE THREAD

**Issue by becauseht** [MikeJMcGuire/hass-blueriiot#3]
Hi Mike, your addons is amazing and works very well, unfortunately i can't get the condictivity parameter, is there any particular reason?in the blueriiot app i have all the details.

![blueriiot](https://github.com/MikeJMcGuire/HASSAddons/assets/9611125/46e2a069-79b4-42e9-bcb4-7c627956814f)
Thanks

**Comment by MikeJMcGuire** [comment]
Hi there, the add-on will attempt to read a conductivity value if it exists. It differs based on whether or not you have a salt water pool from memory. The units either report salinity or conductivity. Yours appears to be reporting salinity.

**Comment by MikeJMcGuire** [comment]
https://blog.mikejmcguire.com/2021/12/30/home-assistant-add-on-for-blueriiot-blue-connect-plus/
There was an update about that for a prior add-on release.
