### ISSUE TITLE
automatic refresh and timestamp

### ISSUE THREAD

**Issue by klona** [MikeJMcGuire/hass-blueriiot#4]
HI, thanks a lot for this code.

How often does it get the new value ? It didnt seems to refresh automatically, so I did an automation to restart the addon every 15 min but this is brutal work around...
I need to explain i don not pay for the pro version and only do manual measurement from the blueriiot apps, to compare with measurement from my ORP probes (on ESP)
Added a python script to save blueriot values along Redox ORP values to try to fit the m together.. (not linear, would have be too easy)

Is that possible to get the date/time info of blueriiot mesurement ?

Thx

**Comment by MikeJMcGuire** [comment]
The add-on refreshes every 30 minutes. When it refreshes, it calls out the current latency - how long between now and when the Blueriiot unit last reported an update. You'll be able to see all of this in the log of the add-on.

**Comment by klona** [comment]
Hi, thanks for the answer. Probably  I did not wait enough.
I removed automation with the restart addon and it will be just fine then.

Did you find anyway to trigger blueriot measurement from HA ? Through ESP perhaps. But it will need reverse engineering on bluetooth I guess... easy to say, not to do..

**Comment by MikeJMcGuire** [comment]
No - I never really looked as the data changes so slowly that more frequent updates would just waste battery. That was when I could rely on SigFox doing an hourly update though.

**Comment by Stefan-83** [comment]
> The add-on refreshes every 30 minutes. When it refreshes, it calls out the current latency - how long between now and when the Blueriiot unit last reported an update. You'll be able to see all of this in the log of the add-on.

Hi @MikeJMcGuire,
Is it possible to reduce the refresh cycle to 10 or 15 minutes?
Thanks, Stefan
